### ISSUE TITLE
SSL error: NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by yagitoshiro** [jiborobot/jibo-sdk#13]
jibo-sdk requires authorization process at first but you can only see a blank Electron app page.

Current Chrome on macOS Sierra will no longer download intermediate certification automatically and that causes NET::ERR_CERT_AUTHORITY_INVALID error at `https://support.jibo.com/c2login`.

You can display login page with `--ignore-certificate-errors` option when you manually open the Electron app.

`$HOME/.atom/packages/jibo-sdk/node_modules/electron-prebuilt-reentrant/dist/Electron.app/Contents/MacOS/Electron $HOME/.atom/packages/jibo-sdk/gating/m.js --ignore-certificate-errors`

The Electron app is to write token to stdout on quit, so above command causes error when you finish authorization, though, at least you can see what the login process is.

Maybe the best solution is to fix SSL/TLS certification on the server, because it's a bit too dangerous to ignore certificate errors on Electron.

**Comment by JohnWRobo** [comment]
Hello @yagitoshiro 

Thank you for getting in touch about this.  The SSL/TLS certification should be fixed now and should be reflected in Chrome on Sierra.

**Comment by yagitoshiro** [comment]
Hi @JohnWRobo,

Thanks, it works!
